version: "3.9"

services:
  app:
    image: 127.0.0.1:5000/app:latest
    build:
      context: ./app/
      dockerfile: Dockerfile-alpine
    ports:
      - "8000:8000"
    depends_on:
      - redis
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  redis:
    image: redis:6-alpine
    ports:
      - "6379"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
