version: "3.9"

services:
  app:
    build: ./app/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

volumes:
  redis:
