version: "3.9"

services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - bridge
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - bridge

volumes:
  redis:

networks:
  bridge:
