FROM python:3.8-alpine

LABEL maintainer="Dong-Young Kim <31337.persona@gmail.com>"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk add --no-cache --virtual .build-deps \
    build-base python3-dev py-pip curl

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps

COPY . .

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0" ]
